### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

**Importing numpy**

In [ ]:
import numpy as np

**TASK 1:-Data Creation:Create suitable arrays to represent students, subjects, and their marks.**

In [ ]:
# Create arrays for student IDs, subject IDs, and marks (2D array)
stud = np.array([[1, 2, 3, 4, 5], [121, 122, 123, 124, 125], [35, 98, 65, 45, 26]])  # used to create the array 1st array is student_id 2nd array is subj_id 3rd array is marks
print("Data Creation:")
print(stud)

Data Creation:
[[  1   2   3   4   5]
 [121 122 123 124 125]
 [ 35  98  65  45  26]]


**TASK 2:- Data Exploration:Explore the properties of these arrays — such as their dimensions, size, and structure.**

In [ ]:
print("Data Exploration:")
print("Array Shape:", stud.shape)
print("Array Size:", stud.size)
print("Array Data Type:", stud.dtype)

Data Exploration:
Array Shape: (3, 5)
Array Size: 15
Array Data Type: int64


**TASK 3:-Data Transformation:Perform necessary reshaping and reorganization of the data to suit various operations.**

In [ ]:
print("Data Transformation:")
# Reshape the array to a 3x5 matrix
reshaped_stud = stud.reshape(3, 5)
print("Reshaped Array:")
print(reshaped_stud)


Data Transformation:
Reshaped Array:
[[  1   2   3   4   5]
 [121 122 123 124 125]
 [ 35  98  65  45  26]]


**TASK4:- Data Combination:Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.**

In [ ]:
print("Data Combination:")
# Combine the original array with another array of new student marks
new_student_marks = np.array([[65,85,67, 98, 70]])  # Ensure the new array has the correct number of columns
combined_stud = np.vstack((stud, new_student_marks))
print("Combined Array:")
print(combined_stud)

Data Combination:
Combined Array:
[[  1   2   3   4   5]
 [121 122 123 124 125]
 [ 35  98  65  45  26]
 [ 65  85  67  98  70]]


**TASK 5:- Data Modification:Apply operations to update marks, remove data, or identify unique information.**

In [ ]:
print("Data Modification:")
# Update the marks of a specific student
combined_stud[2, 2] = 80  # Change the mark of the third student in the third subject to 80 from 65
print("Updated Array:")
print(combined_stud)

Data Modification:
Updated Array:
[[  1   2   3   4   5]
 [121 122 123 124 125]
 [ 35  98  80  45  26]
 [ 65  85  67  98  70]]


**Task 6:- Data Type Handling:Demonstrate how the same data can exist in different data types and how changes affect results.**

In [ ]:
print("Data Type Handling:")
combined_stud = combined_stud.astype(float)   # Convert the marks to a different data type here converted to float
print("Array with Float Data Type:")
print(combined_stud)

Data Type Handling:
Array with Float Data Type:
[[  1.   2.   3.   4.   5.]
 [121. 122. 123. 124. 125.]
 [ 35.  98.  80.  45.  26.]
 [ 65.  85.  67.  98.  70.]]


**Task 7:- Copy and View Behavior:Show the difference between creating a full copy of an array and creating a view of the same data.**

In [ ]:
print("Copy and View Behavior:")
# Create a view of the array
view_stud = combined_stud.view()
print("View of the Array:")
print(view_stud)

# Create a full copy of the array
copy_stud = combined_stud.copy()
print("Full Copy of the Array:")
print(copy_stud)

Copy and View Behavior:
View of the Array:
[[  1.   2.   3.   4.   5.]
 [121. 122. 123. 124. 125.]
 [ 35.  98.  80.  45.  26.]
 [ 65.  85.  67.  98.  70.]]
Full Copy of the Array:
[[  1.   2.   3.   4.   5.]
 [121. 122. 123. 124. 125.]
 [ 35.  98.  80.  45.  26.]
 [ 65.  85.  67.  98.  70.]]
